language: node_js
node_js:
  - "8.5.0"
before_install:
  - echo "deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/ ./" | sudo tee -a /etc/apt/sources.list
  - wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
  - sudo apt-get install -y libzmq3-dev
before_script:
  - npm install
script:
  - npm run lint
  - npm test
