language: node_js
node_js:
  - "8.5.0"

services:
  - docker

install:
  - docker build -t largitor .
  - docker run -d -it --name largitor largitor

script:
  - docker exec largitor npm run lint
  - docker exec largitor npm test
